# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NbmapStoryboard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'nb-ios-maps', '~> 0.0.5'

  target 'NbmapStoryboardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NbmapStoryboardUITests' do
    # Pods for testing
  end

end
